package com.example.shardingseataproxydemo.repository.model;

import lombok.Data;

@Data
public class IotRiskCaptureInformation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iot_risk_capture_information.info_id
     *
     * @mbg.generated Wed Aug 14 18:37:46 CST 2019
     */
    private Integer infoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iot_risk_capture_information.tenant_id
     *
     * @mbg.generated Wed Aug 14 18:37:46 CST 2019
     */
    private Integer tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iot_risk_capture_information.channel
     *
     * @mbg.generated Wed Aug 14 18:37:46 CST 2019
     */
    private String channel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iot_risk_capture_information.person_id
     *
     * @mbg.generated Wed Aug 14 18:37:46 CST 2019
     */
    private String personId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iot_risk_capture_information.trip_id
     *
     * @mbg.generated Wed Aug 14 18:37:46 CST 2019
     */
    private String tripId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iot_risk_capture_information.time
     *
     * @mbg.generated Wed Aug 14 18:37:46 CST 2019
     */
    private Long time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iot_risk_capture_information.push_time
     *
     * @mbg.generated Wed Aug 14 18:37:46 CST 2019
     */
    private Long pushTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iot_risk_capture_information.group_id
     *
     * @mbg.generated Wed Aug 14 18:37:46 CST 2019
     */
    private String groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iot_risk_capture_information.face_id
     *
     * @mbg.generated Wed Aug 14 18:37:46 CST 2019
     */
    private String faceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iot_risk_capture_information.capture_id
     *
     * @mbg.generated Wed Aug 14 18:37:46 CST 2019
     */
    private String captureId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iot_risk_capture_information.face_img
     *
     * @mbg.generated Wed Aug 14 18:37:46 CST 2019
     */
    private String faceImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iot_risk_capture_information.device_id
     *
     * @mbg.generated Wed Aug 14 18:37:46 CST 2019
     */
    private String deviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iot_risk_capture_information.capture_time
     *
     * @mbg.generated Wed Aug 14 18:37:46 CST 2019
     */
    private Long captureTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iot_risk_capture_information.is_first
     *
     * @mbg.generated Wed Aug 14 18:37:46 CST 2019
     */
    private Integer isFirst;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iot_risk_capture_information.hat
     *
     * @mbg.generated Wed Aug 14 18:37:46 CST 2019
     */
    private String hat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iot_risk_capture_information.glass
     *
     * @mbg.generated Wed Aug 14 18:37:46 CST 2019
     */
    private String glass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iot_risk_capture_information.age
     *
     * @mbg.generated Wed Aug 14 18:37:46 CST 2019
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iot_risk_capture_information.gender
     *
     * @mbg.generated Wed Aug 14 18:37:46 CST 2019
     */
    private Integer gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iot_risk_capture_information.helmet
     *
     * @mbg.generated Wed Aug 14 18:37:46 CST 2019
     */
    private String helmet;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iot_risk_capture_information.race
     *
     * @mbg.generated Wed Aug 14 18:37:46 CST 2019
     */
    private String race;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iot_risk_capture_information.pitch
     *
     * @mbg.generated Wed Aug 14 18:37:46 CST 2019
     */
    private Float pitch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iot_risk_capture_information.yaw
     *
     * @mbg.generated Wed Aug 14 18:37:46 CST 2019
     */
    private Float yaw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iot_risk_capture_information.blur
     *
     * @mbg.generated Wed Aug 14 18:37:46 CST 2019
     */
    private Float blur;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iot_risk_capture_information.border
     *
     * @mbg.generated Wed Aug 14 18:37:46 CST 2019
     */
    private Float border;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iot_risk_capture_information.align_score
     *
     * @mbg.generated Wed Aug 14 18:37:46 CST 2019
     */
    private Float alignScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iot_risk_capture_information.image
     *
     * @mbg.generated Wed Aug 14 18:37:46 CST 2019
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iot_risk_capture_information.image_width
     *
     * @mbg.generated Wed Aug 14 18:37:46 CST 2019
     */
    private Integer imageWidth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iot_risk_capture_information.image_height
     *
     * @mbg.generated Wed Aug 14 18:37:46 CST 2019
     */
    private Integer imageHeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iot_risk_capture_information.x
     *
     * @mbg.generated Wed Aug 14 18:37:46 CST 2019
     */
    private Integer x;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iot_risk_capture_information.y
     *
     * @mbg.generated Wed Aug 14 18:37:46 CST 2019
     */
    private Integer y;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iot_risk_capture_information.height
     *
     * @mbg.generated Wed Aug 14 18:37:46 CST 2019
     */
    private Integer height;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column iot_risk_capture_information.width
     *
     * @mbg.generated Wed Aug 14 18:37:46 CST 2019
     */
    private Integer width;
}